version: '3.8'

services:
  notiservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
      - "8444:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development